remote_theme: "godalming123/minimal"
plugins:
- jekyll-remote-theme 
color-scheme: "light"
title: Co-Design Spring School
description: Co-Design Spring School information and registration website.
baseurl: /cdws
defaults:
  - scope:
      path: "images"
    values:
      image: true
