remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Co-Design Winter School
description: Co-Design Winter School information and registration website.
baseurl: /cdws
defaults:
  - scope:
      path: "images"
    values:
      image: true
